### ISSUE TITLE
[Feature] List core family members on profile page

### ISSUE THREAD

**Issue by sohvis** [JustinWingChungHui/okKindred#249]
Add after a list of core family members after the biography section on a profile, i.e.

**Biography**
A biography has not yet been written for this language.

**Family members**

Partner
partners name and link to partners profile page

Parents
parent(s)' name(s) and links to profile page(s)

Siblings
sibling(s)' name(s) and link to profile page(s)

**Comment by JustinWingChungHui** [comment]
Moved to https://github.com/JustinWingChungHui/okKindredUI_typescript/issues/47
