### ISSUE TITLE
[Bug] Map popup shouldn't move the map

### ISSUE THREAD

**Issue by szech** [JustinWingChungHui/okKindred#262]
To reproduce:
- on the map view, zoom in 1 or 2 steps and go to Hong Kong
- there should be a marker for 30 ppl
- click on the marker. The popup is too big and the map is scrolled to some location in Russia

Expected behaviour:
- map does not change location
- popup size should be limited (the size for 9 ppl seems sensible)
- Hidden family members are hinted at or available in some way (maybe a "+5" tile, a scrollable list, or some other mechanism)

browser: chrome 56, PC

**Comment by JustinWingChungHui** [comment]
I think we should implement this clustering plugin for Leaflet (the mapping js library we are using) instead
http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html
