### ISSUE TITLE
[Feature] Migrate to Bootstrap 4

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/okKindred#321]
Loads of breaking changes:
https://getbootstrap.com/docs/4.0/migration/

**Comment by szech** [comment]
😨😓

**Comment by JustinWingChungHui** [comment]
Yeah this is not a small job!

**Comment by JustinWingChungHui** [comment]
http://www.dotnetcurry.com/javascript/1334/migrating-bootstrap-3-to-bootstrap-4
Navbar looks like the biggest chnge from this blog

**Comment by JustinWingChungHui** [comment]
https://youtu.be/_ppokd_g72w
- Change media queries to ems
- Global font size increase
- nav bar on base html
- Carousel changes on landing page
- Thumbnails and panels replaced by cards on landing page
- table classes have changed 
- Glyphicons have gone use class="icon-x"
- Form classes have changed

**Comment by JustinWingChungHui** [comment]
Might be worth a waiting for 4.1 so it stabalises a little

**Comment by JustinWingChungHui** [comment]
Done
