### ISSUE TITLE
[Feature] Checked pwned passwords

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/okKindred#326]
https://haveibeenpwned.com/Passwords

Check on sign up and login

**Comment by szech** [comment]
How to implement this feature?

- get the whole password list ourselves and write a lookup against that
- or use the external api?

the first is obviously preferable but the second one is less work?




================================

  <http://twitter.com/captainszechwan>
<https://www.songkick.com/users/captainszechwan>
<http://www.last.fm/user/CaptainSzechwan>

**Comment by JustinWingChungHui** [comment]
Use the same method that 1Password use.
https://blog.agilebits.com/2018/02/22/finding-pwned-passwords-with-1password/

Hash using SHA-1, send the first 5 characters, and compare against list of matches

**Comment by szech** [comment]
👍

**Comment by JustinWingChungHui** [comment]
Done
