### ISSUE TITLE
Tapping track pad not working in tree view on firefox desktop

### ISSUE THREAD

**Issue by buzzyburrows** [JustinWingChungHui/okKindred#427]
Hi Justin!

Windows 10 x64, track pad and wireless mouse
Tested in Microsoft Edge and Firefox

Tapping the trackpad won't select a person in the tree view.  It does work when clicking the track pad's physical button or using a mouse.  Tapping the trackpad will select the edit button, tabs, links etc, but not people.  Double tapping the trackpad opens the person as it should.

**Comment by JustinWingChungHui** [comment]
Moved to https://github.com/JustinWingChungHui/okKindredUI_typescript/issues/108
